E-Shop-Engine.Website/Models/CartViewModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace E_Shop_Engine.Website.Models
{
    public class CartViewModel
    {
        public virtual IEnumerable<CartLineViewModel> CartLines { get; set; }

        public decimal TotalValue { get; set; }

        public CartViewModel()
        {
            CartLines = new Collection<CartLineViewModel>();
        }
    }
}

E-Shop-Engine.Website/Controllers/CartController.cs
using System.Web.Mvc;
using AutoMapper;
using E_Shop_Engine.Domain.Abstract;
using E_Shop_Engine.Domain.DomainModel;
using E_Shop_Engine.Domain.DomainModel.IdentityModel;
using E_Shop_Engine.Services.Data.Identity.Abstraction;
using E_Shop_Engine.Services.Services;
using E_Shop_Engine.Website.Models;
using NLog;

namespace E_Shop_Engine.Website.Controllers
{
    public class CartController : BaseExtendedController
    {
        private readonly ICartRepository _cartRepository;
        private readonly IProductRepository _productRepository;

        public CartController(
            ICartRepository cartRepository,
            IProductRepository productRepository,
            IAppUserManager userManager,
            IUnitOfWork unitOfWork,
            IMapper mapper)
            : base(unitOfWork, userManager, mapper)
        {
            _cartRepository = cartRepository;
            _productRepository = productRepository;
            _logger = LogManager.GetCurrentClassLogger();
        }

        // GET: /Cart/CountItems
        [Authorize]
        public ActionResult CountItems()
        {
            AppUser user = GetCurrentUser();
            if (user == null)
            {
                return View("_Error", new string[] { GetErrorMessage.NullUser });
            }

            Cart cart = _cartRepository.GetCurrentCart(user);
            int model = _cartRepository.CountItems(cart);

            return PartialView("_Cart", model);
        }

        // GET: /Cart/Details
        [Authorize]
        public ActionResult Details()
        {
            AppUser user = GetCurrentUser();
            if (user == null)
            {
                return View("_Error", new string[] { GetErrorMessage.NullUser });
            }

            Cart cart = _cartRepository.GetCurrentCart(user);
            CartViewModel model = _mapper.Map<Cart, CartViewModel>(cart);
            model.TotalValue = _cartRepository.GetTotalValue(cart);

            return View(model);
        }

        // POST: /Cart/AddItem?id=&quantity=1
        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddItem(int id, int quantity = 1)
        {
            AppUser user = GetCurrentUser();
            if (user == null)
            {
                return View("_Error", new string[] { GetErrorMessage.NullUser });
            }

            Product product = _productRepository.GetById(id);
            Cart cart = _cartRepository.GetCurrentCart(user);

            if (product.NumberInStock > 0)
            {
                product.NumberInStock -= quantity;
                _cartRepository.AddItem(cart, product, quantity);
                _unitOfWork.SaveChanges();
            }
            else
            {
                return View("_Error", new string[] { "Product out of stock!" });
            }

            return RedirectToAction("Details");
        }

        // POST: /Cart/RemoveItem?id=&quantity=1
        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult RemoveItem(int id, int quantity = 1)
        {
            AppUser user = GetCurrentUser();
            if (user == null)
            {
                return View("_Error", new string[] { GetErrorMessage.NullUser });
            }

            Product product = _productRepository.GetById(id);
            Cart cart = _cartRepository.GetCurrentCart(user);

            product.NumberInStock += quantity;
            _cartRepository.RemoveItem(cart, product, quantity);
            _unitOfWork.SaveChanges();

            return RedirectToAction("Details");
        }

        // POST: /Cart/RemoveLine?id&quantity
        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult RemoveLine(int id, int quantity)
        {
            AppUser user = GetCurrentUser();
            if (user == null)
            {
                return View("_Error", new string[] { GetErrorMessage.NullUser });
            }

            Product product = _productRepository.GetById(id);
            Cart cart = _cartRepository.GetCurrentCart(user);

            product.NumberInStock += quantity;
            _cartRepository.RemoveLine(cart, product);
            _unitOfWork.SaveChanges();

            return RedirectToAction("Details");
        }
    }
}

E-Shop-Engine.Website/Controllers/CategoryController.cs
using System.Web.Mvc;
using AutoMapper;
using E_Shop_Engine.Domain.Abstract;
using E_Shop_Engine.Domain.DomainModel;
using E_Shop_Engine.Services.Services;
using E_Shop_Engine.Website.Models;
using NLog;

namespace E_Shop_Engine.Website.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly IRepository<Category> _categoryRepository;

        public CategoryController(IRepository<Category> categoryRepository, IMapper mapper) : base(mapper)
        {
            _categoryRepository = categoryRepository;
            _logger = LogManager.GetCurrentClassLogger();
        }

        // GET: /Category/{name}/{id}
        public ViewResult Details(int id, string sortOrder, bool descending = false)
        {
            if (!string.IsNullOrEmpty(sortOrder))
            {
                SaveSortingState(sortOrder, descending);
            }
            Category category = _categoryRepository.GetById(id);
            CategoryViewModel model = _mapper.Map<CategoryViewModel>(category);

            if (model == null)
            {
                return View("_Error", new string[] { GetErrorMessage.ItemNotFound });
            }

            return View(model);
        }
    }
}

E-Shop-Engine.Website/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using E_Shop_Engine.Domain.Abstract;
using E_Shop_Engine.Domain.DomainModel;
using E_Shop_Engine.Website.CustomFilters;
using E_Shop_Engine.Website.Extensions;
using E_Shop_Engine.Website.Models;
using E_Shop_Engine.Website.Models.Custom;
using NLog;
using X.PagedList;

namespace E_Shop_Engine.Website.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductRepository _productRepository;

        public ProductController(IProductRepository productRepository, IMapper mapper) : base(mapper)
        {
            _productRepository = productRepository;
            _logger = LogManager.GetCurrentClassLogger();
        }

        // GET: /Product/ProductsToPagedList
        [ResetDataDictionaries]
        public PartialViewResult ProductsToPagedList(IEnumerable<ProductViewModel> model, int? page)
        {
            string sortOrder = null;
            bool descending = false;
            if (SortingManager.SortOrder != null)
            {
                sortOrder = SortingManager.SortOrder;
                descending = SortingManager.IsSortDescending;
                SortingManager.SetSorting(sortOrder, descending);
            }

            IEnumerable<ProductViewModel> sortedModel = model.SortBy(x => x.Name, sortOrder, descending);
            int pageNumber = page ?? 1;
            IPagedList<ProductViewModel> viewModel = new PagedList<ProductViewModel>(sortedModel, pageNumber, 9);

            return PartialView("_ProductsDeck", viewModel);
        }

        // GET: /{id}/{name}
        [ReturnUrl]
        public ViewResult Details(int id)
        {
            Product model = _productRepository.GetById(id);
            ProductViewModel viewModel = _mapper.Map<ProductViewModel>(model);

            return View(viewModel);
        }

        // GET: /Product/Search/
        [ResetDataDictionaries]
        public ActionResult Search(int? page, string sortOrder, string search, bool descending = true)
        {
            ManageSearchingTermStatus(ref search);

            IEnumerable<Product> model = GetSearchingResult(search);

            if (model.Count() == 0)
            {
                model = _productRepository.GetAll();
            }

            IEnumerable<ProductViewModel> mappedModel = _mapper.Map<IEnumerable<ProductViewModel>>(model);
            IEnumerable<ProductViewModel> sortedModel = mappedModel.SortBy(x => x.Name, sortOrder, descending);

            int pageNumber = page ?? 1;
            IPagedList<ProductViewModel> viewModel = sortedModel.ToPagedList(pageNumber, 9);

            SaveSortingState(sortOrder, descending, search);

            return View("_ProductsDeck", viewModel);
        }

        [NonAction]
        private IEnumerable<Product> GetSearchingResult(string search)
        {
            IEnumerable<Product> resultName = _productRepository.GetProductsByName(search);
            IEnumerable<Product> resultCatalogNum = _productRepository.GetProductsByCatalogNumber(search);
            IEnumerable<Product> result = resultName.Union(resultCatalogNum).ToList();
            return result;
        }

        // GET: /Product/GetImage?id
        public FileContentResult GetImage(int id)
        {
            Product product = _productRepository.GetById(id);
            if (product?.ImageData != null && product.ImageData.Length != 0)
            {
                return new FileContentResult(product.ImageData, product.ImageMimeType);
            }
            else
            {
                byte[] img = System.IO.File.ReadAllBytes(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Content/default-img.jpg"));

                return new FileContentResult(img, "image/jpg");
            }
        }
    }
}

E-Shop-Engine.Website/Controllers/SubcategoryController.cs
using System.Web.Mvc;
using AutoMapper;
using E_Shop_Engine.Domain.Abstract;
using E_Shop_Engine.Domain.DomainModel;
using E_Shop_Engine.Services.Services;
using E_Shop_Engine.Website.Models;
using NLog;

namespace E_Shop_Engine.Website.Controllers
{
    public class SubcategoryController : BaseController
    {
        private readonly IRepository<Subcategory> _subcategoryRepository;

        public SubcategoryController(IRepository<Subcategory> subcategoryRepository, IMapper mapper) : base(mapper)
        {
            _subcategoryRepository = subcategoryRepository;
            _logger = LogManager.GetCurrentClassLogger();
        }

        // GET: /Category/{mainName}/{subcategoryName}/{subcategoryId}
        public ViewResult Details(int id, string sortOrder, bool descending = false)
        {
            if (!string.IsNullOrEmpty(sortOrder))
            {
                SaveSortingState(sortOrder, descending);
            }
            Subcategory subcategory = _subcategoryRepository.GetById(id);
            SubcategoryViewModel model = _mapper.Map<SubcategoryViewModel>(subcategory);

            if (model == null)
            {
                return View("_Error", new string[] { GetErrorMessage.ItemNotFound });
            }

            return View(model);
        }
    }
}

E-Shop-Engine.Website/Views/Shared/_Cart.cshtml
@model int

    <a href="/Cart/Details" class="nav-link text-white btn btn-primary">
        Cart 
        <span class="badge badge-light">@Model</span>
    </a>   

E-Shop-Engine.Website/Views/Shared/_Categories.cshtml
@model IEnumerable<E_Shop_Engine.Website.Models.CategoryViewModel>

@{
    Layout = null;
}

<nav class="nav flex-column bg-primary w-auto mr-2 mw-min">
    @foreach (var item in Model)
    {
        if (item.Subcategories.Count != 0)
        {
            <div class="dropright">
                @Html.ActionLink(item.Name, "Details", "Category", new { id = item.Id, name = item.Name }, new { @class = "nav-link text-white btn btn-primary dropdown-toggle" })
                <div class="dropdown-menu bg-primary">
                    @foreach (var subcategory in item.Subcategories)
                    {
                        @Html.ActionLink(subcategory.Name, "Details", "Subcategory", new { id = subcategory.Id, mainName = item.Name, subName = subcategory.Name }, new { @class = "text-white btn btn-primary w-100" })
                    }
                </div>
            </div>
        }
        else
        {
            @Html.ActionLink(item.Name, "Details", "Category", new { id = item.Id, name = item.Name }, new { @class = "nav-link text-white btn btn-primary" })
        }
    }
</nav>

E-Shop-Engine.Website/Views/Shared/_Error.cshtml
@model IEnumerable<string>
@{ ViewBag.Title = "Error";}
<div class="alert alert-danger my-2">
    @switch (Model.Count())
    {
        case 0:
            @: Something went wrong. Please try again
            break;
        case 1:
            @Model.First();
            break;
        default:
            @: The following errors were encountered:
            <ul>
                @foreach (string error in Model)
                {
                    <li>@error</li>
                }
            </ul>
            break;
    }
</div>
<div class="text-center">
    @Html.ActionLink("OK", "Index", "Home", null, new { @class = "btn btn-primary" })
</div>

E-Shop-Engine.Website/Views/Shared/_Layout.cshtml
@using E_Shop_Engine.Website.Extensions
@using E_Shop_Engine.Website.Models.Custom;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/Bundles/universal")
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-primary sticky-top">
        <a class="navbar-brand text-white btn btn-primary" href="/Home/Index">@Html.Settings().ShopName</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            @using (Html.BeginForm("Search", "Product", FormMethod.Get, new { @class = "form-inline w-auto m-auto" }))
            {
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
            }

            <ul class="navbar-nav">
                @if (HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    <li class="nav-item active">
                        @Html.Action("CountItems", "Cart")
                    </li>
                    <li class="nav-item active">
                        @Html.ActionLink("Your Account", "Index", "Account", null, new { @class = "nav-link text-white btn btn-primary" })
                    </li>
                }
                <li class="nav-item active">
                    @if (HttpContext.Current.User.IsInRole("Administrators") || HttpContext.Current.User.IsInRole("Staff"))
                    {
                        @Html.ActionLink("Admin Panel", "Index", "OrderAdmin", new { area = "Admin" }, new { @class = "nav-link text-white btn btn-primary" })
                    }
                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link text-white btn btn-primary" })
                </li>
                <li class="nav-item active">
                    @if (!HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Sign In", "Create", "Account", null, new { @class = "nav-link text-white btn btn-primary" })
                    }
                </li>
                <li class="nav-item active">
                    @if (HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Log Out", "Logout", "Account", null, new { @class = "nav-link text-white btn btn-primary" })
                    }
                    else
                    {
                        @Html.ActionLink("Log In", "Login", "Account", null, new { @class = "nav-link text-white btn btn-primary" })
                    }
                </li>
            </ul>
        </div>
    </nav>
    <div class="container-fluid pl-0">
        <div class="d-flex h-90-vh">
            @Html.Action("NavList", "Home")
            <div class="mx-auto" id="content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year</p>
                </footer>
            </div>
        </div>
    </div>
    @RenderSection("Scripts", false)
</body>
</html>

E-Shop-Engine.Website/Views/Shared/_ProductsDeck.cshtml
@using E_Shop_Engine.Website.Extensions;
@using X.PagedList;
@using X.PagedList.Mvc;
@using X.PagedList.Mvc.Common;
@using E_Shop_Engine.Website.Models;
@using E_Shop_Engine.Website.Models.Custom;
@model IPagedList<ProductViewModel>

<div class="dropdown text-right my-2">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Sort By
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="@Request.Url.LocalPath?page=1&sortOrder=Price&descending=true">Price descending</a>
        <a class="dropdown-item" href="@Request.Url.LocalPath?page=1&sortOrder=Price&descending=false">Price</a>
        <a class="dropdown-item" href="@Request.Url.LocalPath?page=1&sortOrder=Name&descending=true">Name descending</a>
        <a class="dropdown-item" href="@Request.Url.LocalPath?page=1&sortOrder=Name&descending=false">Name</a>
        <a class="dropdown-item" href="@Request.Url.LocalPath?page=1&sortOrder=CatalogNumber&descending=true">Catalog Number descending</a>
        <a class="dropdown-item" href="@Request.Url.LocalPath?page=1&sortOrder=CatalogNumber&descending=false">Catalog Number</a>
    </div>
</div>

<div class="card-columns">
    @foreach (var product in Model)
    {
        <div class="card">
            <a href="@Url.Action("Details", "Product", new { id = product.Id, name = product.Name })">
                <div class="w-100">
                    <img id="ImgPreview" class="card-img-top" alt="@product.Name Price: @product.Price.ToString() @Html.Settings().Currency"
                         src="@Url.Action("GetImage", "Product", new { product.Id })" />
                </div>
                <div class="card-body text-center">
                    <h5 class="card-title">@product.Name</h5>
                    <h4 class="card-title">@product.Price @Html.Settings().Currency</h4>
                </div>
            </a>
            <div class="card-body text-center p-0 pb-4">
                @if (product.NumberInStock == 0)
                {
                    <button class="btn btn-danger" disabled>Out of stock!</button>
                }
                else
                {
                    using (Html.BeginForm("AddItem", "Cart", new { id = product.Id }, FormMethod.Post, new { @class = "d-inline" }))
                    {
                        @Html.AntiForgeryToken()
                        <button class="btn btn-success" type="submit">Add to Cart</button>
                    }
                }
            </div>
        </div>
    }
</div>

@Html.PagedListPager((IPagedList)Model, page => { return (Request.Url.LocalPath + "?page=" + page + "&sortOrder=" + SortingManager.SortOrder + "&descending=" + SortingManager.IsSortDescending); }, new PagedListRenderOptions
{
    LiElementClasses = new string[] { "page-item" },
    PageClasses = new string[] { "page-link" },
    UlElementClasses = new string[] { "pagination justify-content-center" },
    LinkToFirstPageFormat = "<<",
    LinkToPreviousPageFormat = "<",
    LinkToNextPageFormat = ">",
    LinkToLastPageFormat = ">>",
    DisplayLinkToFirstPage = PagedListDisplayMode.Always,
    DisplayLinkToLastPage = PagedListDisplayMode.Always,
    DisplayEllipsesWhenNotShowingAllPageNumbers = true,
    MaximumPageNumbersToDisplay = 10
})