E-Shop-Engine.Website/Areas/Admin/Controllers/AccountAdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using E_Shop_Engine.Domain.Abstract;
using E_Shop_Engine.Domain.DomainModel.IdentityModel;
using E_Shop_Engine.Services.Data.Identity.Abstraction;
using E_Shop_Engine.Services.Services;
using E_Shop_Engine.Website.Areas.Admin.Models;
using E_Shop_Engine.Website.Controllers;
using E_Shop_Engine.Website.CustomFilters;
using E_Shop_Engine.Website.Extensions;
using Microsoft.AspNet.Identity;
using NLog;
using X.PagedList;

namespace E_Shop_Engine.Website.Areas.Admin.Controllers
{
    [RouteArea("Admin", AreaPrefix = "Admin")]
    [RoutePrefix("Account")]
    [Route("{action}")]
    [Authorize(Roles = "Administrators, Staff")]
    public class AccountAdminController : BaseExtendedController
    {
        public AccountAdminController(
            IAppUserManager userManager,
            IUnitOfWork unitOfWork,
            IMapper mapper)
            : base(unitOfWork, userManager, mapper)
        {
            _logger = LogManager.GetCurrentClassLogger();
        }

        // GET: Admin/Account/
        [ReturnUrl]
        [ResetDataDictionaries]
        public ActionResult Index(Query query)
        {
            ManageSearchingTermStatus(ref query.search);

            IEnumerable<AppUser> model = GetSearchingResult(query.search);

            if (model.Count() == 0)
            {
                model = _userManager.Users;
            }

            if (query.Reversable)
            {
                ReverseSorting(ref query.descending, query.SortOrder);
            }

            IEnumerable<UserAdminViewModel> mappedModel = _mapper.Map<IEnumerable<UserAdminViewModel>>(model);
            IEnumerable<UserAdminViewModel> sortedModel = mappedModel.SortBy(x => x.Created, query.SortOrder, query.descending);

            int pageNumber = query.Page ?? 1;
            IPagedList<UserAdminViewModel> viewModel = sortedModel.ToPagedList(pageNumber, 25);

            SaveSortingState(query.SortOrder, query.descending, query.search);

            return View(viewModel);
        }

        [NonAction]
        private IEnumerable<AppUser> GetSearchingResult(string search)
        {
            IEnumerable<AppUser> resultEmail = _userManager.FindUsersByEmail(search);
            IEnumerable<AppUser> resultName = _userManager.FindUsersByName(search);
            IEnumerable<AppUser> resultSurname = _userManager.FindUsersBySurname(search);
            IEnumerable<AppUser> result = resultEmail.Union(resultName).Union(resultSurname).ToList();
            return result;
        }

        // GET: Admin/Account/Details?id
        [ReturnUrl]
        public async Task<ActionResult> Details(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                UserAdminViewModel viewModel = _mapper.Map<UserAdminViewModel>(user);
                return View(viewModel);
            }
            return RedirectToAction("Index");
        }

        // POST: Admin/Account/Delete?id
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> Delete(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                // Memorise all child entities.
                user.Carts?.ToString();
                user.Orders?.ToList();
                user.Address?.ToString();

                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("_Error", result.Errors);
                }
            }
            else
            {
                return View("_Error", new string[] { GetErrorMessage.NullUser });
            }
        }

        // GET: Admin/Account/Edit?id
        [ReturnUrl]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> Edit(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            UserAdminViewModel model = _mapper.Map<UserAdminViewModel>(user);
            if (user != null)
            {
                return View(model);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Admin/Account/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> Edit(UserAdminViewModel model)
        {
            AppUser user = await _userManager.FindByIdAsync(model.Id);
            if (user != null)
            {
                user.Email = model.Email;
                user.Name = model.Name;
                user.Surname = model.Surname;
                user.PhoneNumber = model.PhoneNumber;
                user.UserName = model.Email;
                IdentityResult validEmail = await _userManager.UserValidator.ValidateAsync(user);

                if (!validEmail.Succeeded)
                {
                    AddErrorsFromResult(validEmail);
                }
                else if (validEmail.Succeeded)
                {
                    IdentityResult result = await _userManager.UpdateAsync(user);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddErrorsFromResult(result);
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", GetErrorMessage.NullUser);
            }
            return View(model);
        }

        [NonAction]
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

E-Shop-Engine.Website/Areas/Admin/Views/AccountAdmin/Details.cshtml
@using E_Shop_Engine.Website.Extensions;
@model E_Shop_Engine.Website.Areas.Admin.Models.UserAdminViewModel

@{
    ViewBag.Title = "User Details - " + Model.Name + Model.Surname;
}

<h1>User Details - @Model.Name @Model.Surname</h1>

<p>
    @Html.ActionLink("Go Back", "GoBack", "Home", new { area = "" }, new { @class = "btn btn-primary text-white" })
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-secondary" })
</p>

<div class="d-flex flex-nowrap">
    <div class="w-auto mr-2 border-right border-primary">
        <dl>
            <dt>@Html.DisplayNameFor(model => model.Name) @Html.DisplayNameFor(model => model.Surname)</dt>
            <dd>@Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Surname)</dd>

            <dt>@Html.DisplayNameFor(model => model.Email)</dt>
            <dd>@Html.DisplayFor(model => model.Email)</dd>

            <dt>@Html.DisplayNameFor(model => model.PhoneNumber)</dt>
            <dd>@Html.DisplayFor(model => model.PhoneNumber)</dd>

            <dt>@Html.DisplayNameFor(model => model.Created)</dt>
            <dd>@Html.DisplayFor(model => model.Created)</dd>

            <dt>@Html.DisplayNameFor(model => model.Address.Street)</dt>
            <dd>@Html.DisplayFor(model => model.Address.Street)</dd>

            <dt>@Html.DisplayNameFor(model => model.Address.Line1) / @Html.DisplayNameFor(model => model.Address.Line2)</dt>
            <dd>@Html.DisplayFor(model => model.Address.Line1) / @Html.DisplayFor(model => model.Address.Line2)</dd>

            <dt>@Html.DisplayNameFor(model => model.Address.ZipCode) and @Html.DisplayNameFor(model => model.Address.City)</dt>
            <dd>@Html.DisplayFor(model => model.Address.ZipCode) @Html.DisplayFor(model => model.Address.City)</dd>

            <dt>@Html.DisplayNameFor(model => model.Address.State)</dt>
            <dd>@Html.DisplayFor(model => model.Address.State)</dd>

            <dt>@Html.DisplayNameFor(model => model.Address.Country)</dt>
            <dd>@Html.DisplayFor(model => model.Address.Country)</dd>
        </dl>
    </div>
    <div class="w-74 table-responsive">
        <table class="table table-striped table-hover table-light text-center">
            <thead class="table-primary">
                <tr>
                    <th scope="col">
                        ID
                    </th>
                    <th scope="col">
                        Number
                    </th>
                    <th scope="col">
                        Is Paid?
                    </th>
                    <th scope="col">
                        Status
                    </th>
                    <th scope="col">
                        Value
                    </th>
                    <th scope="col">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Orders)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OrderNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsPaid)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OrderStatus)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Payment) @Html.Settings().Currency
                        </td>
                        <td>
                            @Html.ActionLink("Details", "Details", "OrderAdmin", new { id = item.ID }, new { @class = "btn btn-info btn-sm mb-1" })
                            @Html.ActionLink("Edit", "Edit", "OrderAdmin", new { id = item.ID }, new { @class = "btn btn-primary btn-sm mb-1" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

E-Shop-Engine.Website/Areas/Admin/Views/AccountAdmin/Edit.cshtml
@using E_Shop_Engine.Website.Extensions;
@model E_Shop_Engine.Website.Areas.Admin.Models.UserAdminViewModel

@{
    ViewBag.Title = "Edit Account Information";
}

<h1>Edit Account Information</h1>

@using (Html.BeginForm(null, null, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new { @class = "text-danger list-unstyled" })
    <hr />
    @Html.HiddenFor(model => model.Id)

    @Html.TextBoxForExtended(model => model.Name)
    @Html.TextBoxForExtended(model => model.Surname)
    @Html.TextBoxForExtended(model => model.PhoneNumber)
    @Html.TextBoxForExtended(model => model.Email)

    @Html.EndingFormButtons()
}

@section Scripts {
    @Scripts.Render("~/Bundles/validate")
}

E-Shop-Engine.Website/Areas/Admin/Views/AccountAdmin/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc;
@using X.PagedList.Mvc.Common;
@using E_Shop_Engine.Website.Areas.Admin.Models;
@using E_Shop_Engine.Website.Models.Custom;
@model IPagedList<UserAdminViewModel>
@{
    ViewBag.Title = "Accounts";
}

<h1>Accounts</h1>

@using (Html.BeginForm("Index", "AccountAdmin", FormMethod.Get, new { @class = "form-inline my-2" }))
{
    <input class="form-control mr-sm-2 w-75" type="search" placeholder="Search" aria-label="Search" name="search">
    <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
    @Html.ActionLink("Reset", "Index", new { page = 1, sortOrder = "Created", search = "*", descending = false }, new { @class = "btn btn-secondary mx-1 my-2" })
}

<div class=" table-responsive">
    <table class="table table-striped table-hover table-light text-center">
        <thead class="table-primary">
            <tr>
                <th scope="col">@Html.ActionLink("Id", "Index", new { page = 1, sortOrder = "Id", descending = false, reversable = true })</th>
                <th scope="col">@Html.ActionLink("Name", "Index", new { page = 1, sortOrder = "Name", descending = false, reversable = true })</th>
                <th scope="col">@Html.ActionLink("Surname", "Index", new { page = 1, sortOrder = "Surname", descending = false, reversable = true })</th>
                <th scope="col">@Html.ActionLink("Email", "Index", new { page = 1, sortOrder = "Email", descending = false, reversable = true })</th>
                <th scope="col">@Html.ActionLink("Joined", "Index", new { page = 1, sortOrder = "Created", descending = true, reversable = true })</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="4" class="text-center">No User Accounts</td>
                </tr>
            }
            else
            {
                foreach (var user in Model)
                {
                    <tr>
                        <td>@user.Id</td>
                        <td>@user.Name</td>
                        <td>@user.Surname</td>
                        <td>@user.Email</td>
                        <td>@user.Created</td>
                        <td>
                            @Html.ActionLink("Details", "Details", new { id = user.Id }, new { @class = "btn btn-info btn-sm mb-1" })
                            @Html.ActionLink("Edit", "Edit", new { id = user.Id }, new { @class = "btn btn-primary btn-sm mb-1" })
                            @using (Html.BeginForm("Delete", null, FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                @Html.Hidden("id", user.Id)
                                <input type="submit" value="Delete" class="btn btn-danger btn-sm mb-1" onclick="return confirm('Are you sure?')" />
                            }
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

@Html.PagedListPager((IPagedList)Model, page => { return (Request.Url.LocalPath + "?page=" + page + "&sortOrder=" + SortingManager.SortOrder + "&descending=" + SortingManager.IsSortDescending); }, new PagedListRenderOptions
{
    LiElementClasses = new string[] { "page-item" },
    PageClasses = new string[] { "page-link" },
    UlElementClasses = new string[] { "pagination justify-content-center" },
    LinkToFirstPageFormat = "<<",
    LinkToPreviousPageFormat = "<",
    LinkToNextPageFormat = ">",
    LinkToLastPageFormat = ">>",
    DisplayLinkToFirstPage = PagedListDisplayMode.Always,
    DisplayLinkToLastPage = PagedListDisplayMode.Always,
    DisplayEllipsesWhenNotShowingAllPageNumbers = true,
    MaximumPageNumbersToDisplay = 10
})