E-Shop-Engine.Website/Areas/Admin/Models/OrderAdminViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using E_Shop_Engine.Domain.DomainModel;
using E_Shop_Engine.Domain.DomainModel.IdentityModel;
using E_Shop_Engine.Domain.Enumerables;

namespace E_Shop_Engine.Website.Areas.Admin.Models
{
    public class OrderAdminViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Order Number")]
        public string OrderNumber { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Finished { get; set; }

        [Display(Name = "User")]
        public virtual AppUser AppUser { get; set; }

        [Display(Name = "Cart")]
        public virtual Cart Cart { get; set; }
        public decimal Payment { get; set; }

        [Display(Name = "Is Paid")]
        public bool IsPaid { get; set; } = false;

        [Display(Name = "Payment Method")]
        public string PaymentMethod { get; set; }

        [Display(Name = "Transaction Number")]
        public string TransactionNumber { get; set; }

        [Display(Name = "Order Status")]
        [Required]
        public OrderStatus OrderStatus { get; set; }

        public decimal? TotalValue
        {
            get
            {
                return Cart?.CartLines.Sum(x => x.Product.Price * x.Quantity);
            }
        }
    }
}

E-Shop-Engine.Website/Areas/Admin/Controllers/OrderAdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using E_Shop_Engine.Domain.Abstract;
using E_Shop_Engine.Domain.DomainModel;
using E_Shop_Engine.Services.Data.Identity.Abstraction;
using E_Shop_Engine.Website.Areas.Admin.Models;
using E_Shop_Engine.Website.Controllers;
using E_Shop_Engine.Website.CustomFilters;
using E_Shop_Engine.Website.Extensions;
using NLog;
using X.PagedList;

namespace E_Shop_Engine.Website.Areas.Admin.Controllers
{
    [RouteArea("Admin", AreaPrefix = "Admin")]
    [RoutePrefix("Order")]
    [Route("{action}")]
    [Authorize(Roles = "Administrators, Staff")]
    public class OrderAdminController : BaseExtendedController
    {
        private readonly IOrderRepository _orderRepository;
        private readonly IMailingService _mailingRepository;

        public OrderAdminController(
            IOrderRepository orderRepository,
            IMailingService mailingRepository,
            IUnitOfWork unitOfWork,
            IAppUserManager userManager,
            IMapper mapper)
            : base(unitOfWork, userManager, mapper)
        {
            _orderRepository = orderRepository;
            _mailingRepository = mailingRepository;
            _logger = LogManager.GetCurrentClassLogger();
        }

        // GET: Admin/Order
        [ReturnUrl]
        [ResetDataDictionaries]
        public ActionResult Index(Query query)
        {
            ManageSearchingTermStatus(ref query.search);

            IEnumerable<Order> model = GetSearchingResult(query.search);

            if (model.Count() == 0)
            {
                model = _orderRepository.GetAll();
            }

            if (query.Reversable)
            {
                ReverseSorting(ref query.descending, query.SortOrder);
            }

            IEnumerable<OrderAdminViewModel> mappedModel = _mapper.Map<IEnumerable<OrderAdminViewModel>>(model);
            IEnumerable<OrderAdminViewModel> sortedModel = mappedModel.SortBy(x => x.Created, query.SortOrder, query.descending);

            int pageNumber = query.Page ?? 1;
            IPagedList<OrderAdminViewModel> viewModel = sortedModel.ToPagedList(pageNumber, 25);

            SaveSortingState(query.SortOrder, query.descending, query.search);

            return View(viewModel);
        }

        [NonAction]
        private IEnumerable<Order> GetSearchingResult(string search)
        {
            IEnumerable<Order> resultOrderNumber = _orderRepository.FindByOrderNumber(search);
            IEnumerable<Order> resultTransactionNumber = _orderRepository.FindByTransactionNumber(search);
            IEnumerable<Order> model = resultOrderNumber.Union(resultTransactionNumber).ToList();
            return model;
        }

        // GET: Admin/Order/Details?id
        [ReturnUrl]
        public ActionResult Details(int id)
        {
            Order order = _orderRepository.GetById(id);
            OrderAdminViewModel model = _mapper.Map<OrderAdminViewModel>(order);

            return View(model);
        }

        // GET: Admin/Order/Edit?id
        [ReturnUrl]
        public ViewResult Edit(int id)
        {
            Order order = _orderRepository.GetById(id);
            OrderAdminViewModel model = _mapper.Map<OrderAdminViewModel>(order);

            return View(model);
        }

        // POST: Admin/Order/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OrderAdminViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Order order = _orderRepository.GetById(model.Id);
            order.Finished = model.Finished;
            order.OrderStatus = model.OrderStatus;

            _orderRepository.Update(_mapper.Map<Order>(order));
            _mailingRepository.OrderChangedStatusMail(order.AppUser.Email, order.OrderNumber, order.OrderStatus.ToString(), "Order " + order.OrderNumber + " status updated");
            _unitOfWork.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

E-Shop-Engine.Website/Areas/Admin/Views/OrderAdmin/Details.cshtml
@using E_Shop_Engine.Utilities.Extensions;
@using E_Shop_Engine.Website.Extensions;
@model E_Shop_Engine.Website.Areas.Admin.Models.OrderAdminViewModel

@{
    ViewBag.Title = "Order " + Model.OrderNumber + " Details";
}

<h1>Order @Model.OrderNumber Details</h1>

<p>
    @Html.ActionLink("Go Back", "GoBack", "Home", new { area = "" }, new { @class = "btn btn-primary text-white" })
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-secondary" })
</p>

<div class="d-flex flex-nowrap">
    <div class="w-auto mr-2 border-right border-primary">
        <dl class="clickable-row pointer" data-href="/Admin/Account/Details/@Model.AppUser.Id">
            <dt>User Id</dt>
            <dd>@Html.DisplayFor(model => model.AppUser.Id)</dd>

            <dt>@Html.DisplayNameFor(model => model.AppUser.Name) @Html.DisplayNameFor(model => model.AppUser.Surname)</dt>
            <dd>@Html.DisplayFor(model => model.AppUser.Name) @Html.DisplayFor(model => model.AppUser.Surname)</dd>

            <dt>@Html.DisplayNameFor(model => model.AppUser.Email)</dt>
            <dd>@Html.DisplayFor(model => model.AppUser.Email)</dd>
        </dl>
        <dl>
            <dt>@Html.DisplayNameFor(model => model.OrderNumber)</dt>
            <dd>@Html.DisplayFor(model => model.OrderNumber)</dd>

            <dt>@Html.DisplayNameFor(model => model.Created)</dt>
            <dd>@Html.DisplayFor(model => model.Created)</dd>

            <dt>@Html.DisplayNameFor(model => model.Finished)</dt>
            <dd>@Html.DisplayFor(model => model.Finished)</dd>

            <dt>@Html.DisplayNameFor(model => model.IsPaid)</dt>
            <dd>@Html.DisplayFor(model => model.IsPaid)</dd>

            <dt>@Html.DisplayNameFor(model => model.OrderStatus)</dt>
            <dd>
                @{
                    var orderStatus = Model.OrderStatus.GetDisplayName();
                    orderStatus = orderStatus == null ? Model.OrderStatus.ToString() : orderStatus;
                }
                @Html.DisplayFor(model => orderStatus)
            </dd>

            <dt>@Html.DisplayNameFor(model => model.PaymentMethod)</dt>
            <dd>
                @{
                    var name = Model.PaymentMethod.GetDisplayName();
                    name = name == null ? Model.PaymentMethod.ToString() : name;
                }
                @Html.DisplayFor(model => name)
            </dd>
            <dt>@Html.DisplayNameFor(model => model.TransactionNumber)</dt>
            <dd>@Html.DisplayFor(model => model.TransactionNumber)</dd>
        </dl>
    </div>
    <div class="w-74 table-responsive">
        <table class="table table-striped table-hover table-light text-center">
            <thead class="table-primary">
                <tr>
                    <th scope="col">
                        Catalog Number
                    </th>
                    <th scope="col">
                        Name
                    </th>
                    <th scope="col">
                        Quantity
                    </th>
                    <th scope="col">
                        Price
                    </th>
                    <th scope="col">
                        Value
                    </th>
                    <th scope="col">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Cart.CartLines)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Product.CatalogNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Product.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Product.Price) @Html.Settings().Currency
                        </td>
                        <td>
                            @(item.Product.Price * item.Quantity) @Html.Settings().Currency
                        </td>
                        <td>
                            @Html.ActionLink("Details", "Details", "ProductAdmin", new { id = item.Product.ID }, new { @class = "btn btn-info btn-sm mb-1" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <h3>Total value: @Model.Payment @Html.Settings().Currency</h3>
    </div>
</div>

@section Scripts
{
    <script src="~/Scripts/custom/clickable-row.js" type="text/javascript"></script>
}

E-Shop-Engine.Website/Areas/Admin/Views/OrderAdmin/Edit.cshtml
@using E_Shop_Engine.Website.Extensions;
@model E_Shop_Engine.Website.Areas.Admin.Models.OrderAdminViewModel

@{
    ViewBag.Title = "Order " + Model.OrderNumber;
}

<h1>Order @Model.OrderNumber</h1>

@using (Html.BeginForm(null, null, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new { @class = "text-danger list-unstyled", id = "validation-summary" })
    <hr />
    @Html.HiddenFor(model => model.Id)

    <fieldset disabled>
        @Html.TextBoxForExtended(model => model.OrderNumber)
        @Html.TextBoxForExtended(model => model.Created)
        @Html.TextBoxForExtended(model => model.PaymentMethod)
        @Html.TextBoxForExtended(model => model.IsPaid)
        @Html.TextBoxForExtended(model => model.TransactionNumber)
    </fieldset>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            @Html.LabelFor(model => model.Finished, new { @class = "input-group-text" })
        </div>
        <input type="date" class="form-control single-line" name="Finished" id="Finished" />
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            @Html.LabelFor(model => model.OrderStatus, new { @class = "input-group-text" })
        </div>
        @Html.EnumDropDownListFor(model => model.OrderStatus, "Select order status", new { @class = "form-control" })
    </div>

    @Html.EndingFormButtons()
}

@section Scripts {
    @Scripts.Render("~/Bundles/validate")
}

E-Shop-Engine.Website/Areas/Admin/Views/OrderAdmin/Index.cshtml
@using E_Shop_Engine.Utilities.Extensions;
@using E_Shop_Engine.Website.Extensions;
@using X.PagedList;
@using X.PagedList.Mvc;
@using X.PagedList.Mvc.Common;
@using E_Shop_Engine.Website.Areas.Admin.Models;
@using E_Shop_Engine.Website.Models.Custom;
@model IPagedList<OrderAdminViewModel>

@{
    ViewBag.Title = "Orders";
}

<h1>Orders</h1>

@using (Html.BeginForm("Index", "OrderAdmin", FormMethod.Get, new { @class = "form-inline my-2" }))
{
    <input class="form-control mr-sm-2 w-75" type="search" placeholder="Search" aria-label="Search" name="search">
    <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
    @Html.ActionLink("Reset", "Index", new { page = 1, sortOrder = "OrderNumber", search = "*", descending = false }, new { @class = "btn btn-secondary mx-1 my-2" })
}

<div class=" table-responsive">
    <table class="table table-striped table-hover table-light text-center">
        <thead class="table-primary">
            <tr>
                <th scope="col">
                    @Html.ActionLink("Id", "Index", new { page = 1, sortOrder = "Id", search = SortingManager.SearchTerm, descending = false, reversable = true })
                </th>
                <th scope="col">
                    @Html.ActionLink("Order Number", "Index", new { page = 1, sortOrder = "OrderNumber", search = SortingManager.SearchTerm, descending = false, reversable = true })
                </th>
                <th scope="col">
                    @Html.ActionLink("Transaction Number", "Index", new { page = 1, sortOrder = "TransactionNumber", search = SortingManager.SearchTerm, descending = false, reversable = true })
                </th>
                <th scope="col">
                    @Html.ActionLink("Is Paid?", "Index", new { page = 1, sortOrder = "IsPaid", search = SortingManager.SearchTerm, descending = true, reversable = true })
                </th>
                <th scope="col">
                    @Html.ActionLink("Status", "Index", new { page = 1, sortOrder = "OrderStatus", search = SortingManager.SearchTerm, descending = false, reversable = true })
                </th>
                <th scope="col">
                    @Html.ActionLink("Value", "Index", new { page = 1, sortOrder = "Payment", search = SortingManager.SearchTerm, descending = true, reversable = true })
                </th>
                <th scope="col">
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TransactionNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsPaid)
                    </td>
                    <td>
                        @{
                            var name = item.OrderStatus.GetDisplayName();
                            name = name == null ? item.OrderStatus.ToString() : name;
                        }
                        @Html.DisplayFor(modelItem => name)
                    </td>
                    <td>
                        @item.Payment @Html.Settings().Currency
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-sm mb-1" })
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-sm mb-1" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@Html.PagedListPager((IPagedList)Model, page => { return (Request.Url.LocalPath + "?page=" + page + "&sortOrder=" + SortingManager.SortOrder + "&descending=" + SortingManager.IsSortDescending); }, new PagedListRenderOptions
{
    LiElementClasses = new string[] { "page-item" },
    PageClasses = new string[] { "page-link" },
    UlElementClasses = new string[] { "pagination justify-content-center" },
    LinkToFirstPageFormat = "<<",
    LinkToPreviousPageFormat = "<",
    LinkToNextPageFormat = ">",
    LinkToLastPageFormat = ">>",
    DisplayLinkToFirstPage = PagedListDisplayMode.Always,
    DisplayLinkToLastPage = PagedListDisplayMode.Always,
    DisplayEllipsesWhenNotShowingAllPageNumbers = true,
    MaximumPageNumbersToDisplay = 10
})